version: '3'
services:
    genome-api:
        build: .
        image: genome-api
        command: genome-api
        expose:
            - "8081"
    swagger-ui:
        container_name: swagger-ui
        image: swaggerapi/swagger-ui
        environment:
          - API_URL=http://192.168.99.100/api/swagger.json
        expose:
            - "8080"
    nginx:
        build: ./nginx
        image: nginx
        ports:
            - "80:80"
            - "7687:7687"
        depends_on:
            - genome-api
    neo4j_db:
        container_name: neo4j_db
        image: neo4j
        expose:
            - "7474"
            - "7687"
        volumes:
            - ${HOME}/genome-api/neo4j-persist/${GENOME_ENV}/data:/data:cached
            - ${HOME}/genome-api/neo4j-persist/${GENOME_ENV}/logs:/logs:cached
        environment:
            - NEO4J_AUTH=none